[package]
name = "client"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
blind-rsa-signatures = "0.17.2"
anyhow = "1.0.104"
base64 = "0.21.0"
getrandom = { version = "0.4", features = ["wasm_js"] }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
