[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
blind-rsa-signatures = "0.17.2"
clap = { version = "4.6.7", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
base64 = "0.21.0"
tokio = { version = "1.53.1", features = ["full"] }
sqlx = { version = "0.9", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "macros",
    "uuid",
    "chrono",
] }
dotenvy = "0.15.7"
reqwest = { version = "0.13.5", features = ["form", "json", "query"] }
axum = "0.8.9"
tower = { version = "0.5.3", features = ["full"] }
tower-http = { version = "0.7.1", features = ["trace"] }
tracing-subscriber = "0.3.23"
tracing = "0.1.44"
getrandom = "0.4.3"
rand = "0.10.3"
axum-extra = { version = "0.12.6", features = ["cookie"] }
